/**
 * Legal copy sourced from BestBond Terms & Privacy (May 2026).
 * FILE_0853.docx / FILE_4975.pdf — keep in sync with published documents.
 */
export const LEGAL_UPDATED_ON = 'May 2026';

export const TERMS_AND_CONDITIONS_TITLE = 'Terms of Service';

export const PRIVACY_POLICY_TITLE = 'Privacy Policy';

export const LEGAL_DOC_SUBTITLE =
  'BestBond Rewards Program Mobile Application & Admin Management System';

export const TERMS_AND_CONDITIONS_BODY = `TERMS & CONDITIONS
BestBond Rewards Program Mobile Application
Last Updated: May 2026
Welcome to the BestBond Rewards Program (“Program”) operated by BestBond. The Program is designed exclusively for contractors, painters, workers, and authorized applicators using BestBond products to earn reward points through QR coupon scanning and redeem them against eligible gifts available within the Application.
By registering, accessing, or using the Application, you agree to comply with these Terms & Conditions.

1. DEFINITIONS
• Company / BestBond / We / Us / Our refers to BestBond and its authorized representatives.
• Application refers to the BestBond Rewards mobile application and admin management system.
• User refers to registered workers, painters, contractors, applicators, or authorized participants enrolled in the Program.
• Coupon refers to a unique QR-enabled reward code generated by the Company.
• Points refers to reward points credited to a user wallet after successful coupon validation.
• Wallet refers to the digital in-app reward balance available to eligible users.
• Redemption refers to the exchange of accumulated reward points for gifts or rewards available in the Program.

2. ELIGIBILITY
The Program is available only to:
• Contractors
• Painters
• Applicators
• Workers associated with BestBond products
To participate:
• Users must provide valid registration details and mobile numbers.
• Users must be at least 18 years old.
• Users may be required to provide verification documents for identity validation.
BestBond reserves the right to approve, reject, suspend, or terminate any user account at its discretion.

3. USER ACCOUNT RESPONSIBILITY
Users are responsible for:
• Maintaining accurate profile information
• Securing OTP access and login credentials
• Ensuring only authorized personal use of the account
The Company shall not be liable for:
• Unauthorized account access due to user negligence
• Incorrect redemption details submitted by users
• Loss of rewards caused by inaccurate information
Duplicate or fraudulent accounts may be suspended permanently.

4. QR COUPON SYSTEM
The Program operates through a QR-based coupon validation system.
4.1 Coupon Structure
Each coupon contains:
• Unique coupon ID
• QR code
• Assigned reward value
4.2 Coupon Rules
• Coupons are valid for one-time use only.
• Once scanned successfully, the coupon becomes permanently inactive.
• Expired, damaged, duplicated, manipulated, or unauthorized coupons will be rejected.
4.3 Coupon Usage Flow
1. User scans the QR code through the Application.
2. System validates coupon authenticity.
3. Reward points are credited to the wallet.
4. Coupon becomes inactive after successful validation.

4.4 Fraud Prevention
The following activities are strictly prohibited:
• Duplicate scanning attempts
• Fake or manipulated QR codes
• Unauthorized coupon circulation
• System abuse or misuse
BestBond reserves the right to:
• Reverse points
• Reject redemption requests
• Suspend accounts
• Permanently block users
• Initiate legal proceedings where applicable

5. REWARD WALLET
• Valid coupon scans will credit reward points to the user wallet.
• Reward points are non-transferable and cannot be exchanged for cash.
• Wallet balances remain under the control of BestBond.
• Points may expire based on promotional or operational policies.
BestBond reserves the right to:
• Modify reward structures
• Update coupon values
• Change redemption criteria
• Introduce or discontinue campaigns without prior notice

6. REDEMPTION POLICY
The Program follows a slab-based redemption structure.
6.1 Redemption Eligibility
Users may redeem points only against rewards displayed within the Application and subject to available redemption slabs.
6.2 Available Gifts & Redemption Slabs
The following rewards are currently available under the Program:
[[GIFT_SLAB_TABLE]]

6.3 Redemption Process
1. User selects a reward from the Application.
2. Redemption request is submitted.
3. Admin verifies eligibility and reward availability.
4. Approved rewards are processed for dispatch or delivery.

6.4 Redemption Approval
All redemption requests are subject to:
• Internal verification
• Fraud screening
• Stock availability
• Account validation
BestBond reserves the right to reject any redemption request deemed suspicious or invalid.
6.5 Reward Delivery
• Reward dispatch timelines may vary depending on location and availability.
• Gifts shown in the Application are indicative and may vary slightly in color, model, or specifications depending on market availability.
• In case a listed product is discontinued or unavailable, BestBond reserves the right to provide an equivalent product of similar value.
6.6 Non-Cash Redemption
Rewards:
• Cannot be exchanged for cash
• Cannot be transferred to another user
• Cannot be resold through the Program

7. TRANSACTION HISTORY & SUPPORT
Users may access:
• Wallet balance
• Coupon scan history
• Redemption status
• Reward history
• Support contact information
Transaction records displayed in the Application shall be considered final unless proven otherwise.

8. ADMIN MANAGEMENT SYSTEM
The Program includes role-based administrative controls.
8.1 Super Admin
Authorized to:
• Generate coupons
• Manage users
• Access analytics
• Approve or reject redemptions
• Monitor system activities
8.2 Operational Admin
Authorized to:
• Process redemptions
• Coordinate reward dispatch
• Assist users
• Handle operational support
All admin activities may be monitored and logged for audit and security purposes.

9. ANALYTICS & REPORTING
The platform may maintain centralized analytics including:
• Coupons generated
• Coupons redeemed
• Points issued
• Redemption patterns
• Active user statistics
• Reward distribution metrics
These analytics help improve operational efficiency and campaign performance.

10. INTELLECTUAL PROPERTY
All platform assets including:
• Logos
• Branding
• QR systems
• Software
• Application UI/UX
• Reward structures
• Databases
remain the exclusive intellectual property of BestBond.
Unauthorized reproduction or distribution is prohibited.

11. LIMITATION OF LIABILITY
BestBond shall not be liable for:
• Temporary system downtime
• Failed scans caused by damaged QR codes
• Network interruptions
• Delayed reward deliveries
• Third-party logistics issues
• Unauthorized account usage due to user negligence
The Application is provided on an “as available” basis.

12. ACCOUNT SUSPENSION & TERMINATION
BestBond reserves the right to:
• Suspend or terminate accounts
• Cancel wallet balances
• Reject redemptions
• Restrict platform access
in case of policy violations, fraud, or misuse of the Program.

13. MODIFICATIONS TO TERMS
BestBond reserves the right to:
• Modify these Terms
• Update rewards and redemption structures
• Change coupon policies
• Revise operational workflows
without prior notice.
Continued usage of the Application constitutes acceptance of updated Terms.

14. GOVERNING LAW
These Terms shall be governed by the laws of India.
Any disputes shall fall under the jurisdiction of competent courts located in Kerala, India.
`;

export const PRIVACY_POLICY_BODY = `PRIVACY POLICY
BestBond Rewards Program Mobile Application
Last Updated: May 2026
BestBond is committed to protecting user privacy and maintaining the confidentiality of personal information collected through the BestBond Rewards Program.
This Privacy Policy explains how user information is collected, used, stored, and protected.

1. INFORMATION WE COLLECT
1.1 Personal Information
We may collect:
• Full name
• Mobile number
• Email address
• Address details
• Worker or contractor identification details

1.2 Reward Program Information
We may collect:
• QR scan activity
• Coupon usage history
• Wallet balances
• Redemption requests
• Transaction history
• Reward preferences

1.3 Technical Information
The Application may automatically collect:
• Device model
• Operating system
• IP address
• App version
• Device identifiers
• Network information
• Crash reports

2. HOW WE USE INFORMATION
Collected information may be used to:
• Register and manage user accounts
• Validate QR coupon scans
• Credit reward points
• Process reward redemptions
• Deliver gifts and rewards
• Provide support services
• Improve platform performance
• Conduct operational analytics
• Prevent fraud and abuse
• Communicate updates and promotional offers

3. CAMERA & DEVICE PERMISSIONS
The Application may request access to:
• Camera – for QR code scanning
• Storage – for temporary file handling or uploads
• Notifications – for redemption and reward alerts
Permissions are used strictly for application functionality.

4. COUPON & TRANSACTION SECURITY
Every coupon:
• Is uniquely generated
• Is validated against the central system
• Can only be used once
All reward transactions are securely logged for:
• Fraud prevention
• Audit purposes
• Redemption verification
• Customer support

5. INFORMATION SHARING
We do not sell user data.
Information may be shared with:
• Authorized operational teams
• Delivery and logistics partners
• Cloud hosting providers
• SMS gateway providers
• Legal authorities where required by law
All third-party providers are expected to maintain confidentiality standards.

6. DATA SECURITY
We implement reasonable security measures including:
• Secure authentication systems
• Encrypted communication
• Role-based admin access
• Activity monitoring and audit logs
However, no online platform can guarantee complete security.

7. DATA RETENTION
User information may be retained:
• For operational purposes
• To maintain redemption records
• For fraud prevention
• For legal and audit compliance
Certain records may continue to be retained even after account deactivation where legally required.

8. USER RIGHTS
Users may request:
• Access to their personal information
• Correction of inaccurate data
• Account deactivation
• Assistance regarding redemption disputes
Requests may be submitted through the support details available within the Application.

9. THIRD-PARTY SERVICES
The Application may integrate with:
• SMS providers
• Push notification services
• Analytics tools
• Cloud infrastructure providers
• Delivery partners
Such services may operate under their own policies and terms.

10. CHILDREN’S PRIVACY
The Application is intended only for individuals above 18 years of age.
We do not knowingly collect information from minors.

11. POLICY UPDATES
BestBond reserves the right to modify this Privacy Policy periodically.
Updated versions will be published within the Application and related official platforms.

12. CONTACT INFORMATION
For queries regarding:
• Rewards
• Redemptions
• Privacy concerns
• Account support

please contact:
BestBond Rewards Support Team

Registered Office Address:
60, Gottamaranahalli,
Signeagrahara Road
Behind Fruits Market,
Huskur Post
Bengaluru 560 099

Customer Support Number:
+91 9686191514

Support Email:
bestbond03@yahoo.com

Website:
www.bestbond.in
`;
